# Site settings
title: Lucy & Ethel Do Estate Sales
email: scal36@tx.rr.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/lucyethelsales" # the subpath of your site, e.g. /blog/
url: "http://lucyethelsales.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
